### ISSUE TITLE
select micro-controller for Management System

### ISSUE THREAD

**Issue by jonsnow1357** [agathisproject/pinus-flexilis#1]
Proposing dsPIC33CH512MP205:
  - 16b arch
  - 512 kB Flash / 48 kB RAM
  - 39 max IO pins
  - 3 UART / 3 SPI / 3 I2C

**Comment by mariusdraghia** [comment]
Hardware looks good - close to perfect. Some related thoughts:

"Maybe" short on pins for controlling a SoM like a COMe Mini or directly a CPU/chipset; dsPIC33CH512MP208 is only larger, similar Digikey price.

At some point, GPIO pin logic/mapping across various modules may become an issue if an unified software is considered; I have no clear idea what I'm talking about.

**Comment by jonsnow1357** [comment]
reconsidering this due to some difficulties in porting FreeRTOS to dsPIC33CH family.
Looking at PIC24EP512GP806 right now ...

**Comment by jonsnow1357** [comment]
Looking at dsPIC33FJ256GP506A due to crappy eval boards available for the PIC24***.

**Comment by jonsnow1357** [comment]
and we got to PIC24FJ256GA705
- supported by Curiosity board (DM240016)
- supported by MPLAB Code Configurator
- supported by FreeRTOS

**Comment by mariusdraghia** [comment]
- must have 3x I2C (two for trunk and one for local)
- PIC33CH is, for some reason(other than temperature range), recommended for automotive, while PIC24FJ is not.
- high pin count package may avoid the apparition of many uC variants and pin muxing limitations.

**Comment by jonsnow1357** [comment]
not valid for this repo anymore
